// import {
//     UserOutlined,
//     SettingOutlined,
//     BookOutlined,
//     AppstoreOutlined,
//     MoneyCollectOutlined,
//     NotificationOutlined,
//     MailOutlined,
//     SolutionOutlined,
//     CalendarOutlined,
//     FileTextOutlined,
//     GlobalOutlined
//   } from "@ant-design/icons";
  
//   export const modules = [
//     { name: "Dashboard", route: "/", Icons: AppstoreOutlined,roles:[0,1,2,3,4,5,6] },
//     {
//       name: "Library",
//       route: "/library",
//       Icons: BookOutlined,
//       roles:[0,1,2,3,4,5,6],
//       subModules: [
//         { name: "Manage Books", route: "/library/manage-books", Icons: FileTextOutlined,roles:[0,1,2,3,4,5] },
//         { name: "Library Report", route: "/library/report", Icons: FileTextOutlined,roles:[0,1,2,3,4,5] },
//         { name: "Lend a Book", route: "/library/lend", Icons: FileTextOutlined,roles:[0,1,2,3,4,5]},
//         { name: "Library Statistics", route: "/library/statistics", Icons: FileTextOutlined,roles:[0,1,2,3,4,5] },
//         { name: "Book Reservation", route: "/library/reservation", Icons: FileTextOutlined,roles:[0,1,2,3,4,5,6] },
//         { name: "Fines", route: "/library/fines", Icons: MoneyCollectOutlined,roles:[0,1,2,3,4,5,6] },
//         { name: "Digital Library", route: "/library/digital-library", Icons: GlobalOutlined,roles:[0,1,2,3,4,5,6] },
//       ], 
//     },
//     {
//       name: "Class Room",
//       route: "/classrooms",
//       Icons: AppstoreOutlined,
//       roles:[0,1,2,3,5,6],
//       subModules: [
//         { name: "Manage Class Room", route: "/classrooms/manage-class", Icons: AppstoreOutlined,roles:[0,1,2,3,5] },
//         { name: "Manage Subject", route: "/classrooms/manage-subject", Icons: AppstoreOutlined,roles:[0,1,2,3,5] },
//         { name: "Time Table", route: "/classrooms/time-table", Icons: CalendarOutlined,roles:[5,6] },
//         { name: "Teacher Time Table", route: "/classrooms/teachers-time-table", Icons: CalendarOutlined,roles:[5] },
//         { name: "Manage Time Table", route: "/classrooms/manage-time-table", Icons: CalendarOutlined,roles:[0,1,2,3,5] },
//         { name: "Attendance", route: "/classrooms/attendance", Icons: CalendarOutlined,roles:[2,3,4,5,6] },
//         { name: "Attendance Report", route: "/classrooms/attendance-report", Icons: CalendarOutlined,roles:[0,1,2,3,4,5] },
//         { name: "Take Attendance", route: "/classrooms/take-attendance", Icons: CalendarOutlined,roles:[0,1,2,3,5] },
//         { name: "Students Performance", route: "/classrooms/students-performance", Icons: FileTextOutlined,roles:[0,1,2,3,5] },
//         { name: "Syllabus", route: "/classrooms/syllabus", Icons: FileTextOutlined,roles:[6] },
//         { name: "Manage Syllabus", route: "/classrooms/manage-syllabus", Icons: FileTextOutlined,roles:[0,1,2,3,5] },
//         { name: "Manage Study Material", route: "/classrooms/manage-study-material", Icons: FileTextOutlined,roles:[0,1,2,3,5] },
//         { name: "Study Materials", route: "/classrooms/study-material", Icons: FileTextOutlined,roles:[6] },
//       ],
//     },
//     {
//       name: "Accounts",
//       route: "/accounts",
//       Icons: MoneyCollectOutlined,
//       roles:[0,1,4],
//       subModules: [
//         { name: "Bill and Receipt", route: "/accounts/bill-receipt", Icons: MoneyCollectOutlined,roles:[0,1,4] },
//         { name: "Fees Structure", route: "/accounts/fee-structure", Icons: MoneyCollectOutlined,roles:[0,1,4] },
//         { name: "Students Due Date", route: "/accounts/student-due-date", Icons: MoneyCollectOutlined,roles:[0,1,4] },
//         { name: "Salary Management", route: "/accounts/salary-management", Icons: MoneyCollectOutlined,roles:[0,1,4] },
//         { name: "Accounts Report", route: "/accounts/accounts-report", Icons: FileTextOutlined,roles:[0,1,4] },
//         { name: "Statistics", route: "/accounts/statistics", Icons: FileTextOutlined,roles:[0,1,4] },
//       ],
//     },
//     { name: "Notifications", route: "/notifications", Icons: NotificationOutlined,roles:[0,1,2,3,4,5,6] },
//     { name: "Complaints", route: "/complaints", Icons: MailOutlined,roles:[0,1,2,3,4,5,6] },
//     {
//       name: "Users",
//       route: "/users",
//       Icons: UserOutlined,
//       roles:[0,1,2,3,4,5],
//       subModules: [
//         { name: "Students", route: "/users/students", Icons: UserOutlined,roles:[0,1,2,3,4,5] },
//         { name: "Staff", route: "/users/staff", Icons: UserOutlined,roles:[0,1,2,3] },
//         { name: "Admission", route: "/users/admission", Icons: UserOutlined,roles:[0,1,4] },
//       ],
//     },
//     {
//       name: "Exams",
//       route: "/exams",
//       Icons: SolutionOutlined,
//       roles:[0,1,2,3,4,5,6],
//       subModules: [
//         { name: "Online Exams", route: "/exams/online", Icons: SolutionOutlined,roles:[0,1,2,3,5] },
//         { name: "Offline Exams", route: "/exams/offline", Icons: SolutionOutlined,roles:[0,1,2,3,5] },
//         { name: "Exam Time Table", route: "/exams/online", Icons: SolutionOutlined,roles:[5,6] },
//         { name: "Create Online Exams", route: "/exams/create-online", Icons: SolutionOutlined,roles:[0,1,2,3,5] },
//         { name: "Create Offline Exams", route: "/exams/create-offline", Icons: SolutionOutlined,roles:[0,1,2,3,5] },
//         { name: "Exams Time Table Management", route: "/exams/time-table-management", Icons: SolutionOutlined,roles:[0,1,2,3,5] },
//         { name: "Result", route: "/exams/result", Icons: FileTextOutlined,roles:[0,1,2,3,5] },
//         { name: "GradeBook", route: "/exams/grade-book", Icons: FileTextOutlined,roles:[6] },
//       ],
//     },
//     {
//       name: "Other",
//       route: "/other",
//       Icons: GlobalOutlined,
//       roles:[0,1,2,3,4,5,6],
//       subModules: [
//         { name: "Travel", Icons: GlobalOutlined,route:"/travel",roles:[0,1,2,3,4,5,6] },
//         { name: "Mess", Icons: GlobalOutlined,route:"/canteen",roles:[0,1,2,3,4,5,6] },
//       ],
//     },
//     { name: "Settings", route: "/settings", Icons: SettingOutlined,roles:[0,1,2,3,4,5,6] },
//   ];
  
  